name: keep-presence
version: '1.0.7'
summary: Keep Presence
description: |
  This program moves the mouse or press a key when it detects that you are away.
  It won't do anything if you are using your computer.
  Useful to trick your machine to think you are still working with it.
icon: snap/gui/logo.png
grade: stable
confinement: strict
base: core18

parts:
  copy-stuff:
    plugin: dump
    source: ./src
  keep-presence:
    plugin: python
    python-version: python3
    source: .
  dlib:
    plugin: python
    python-packages:
      - pynput

apps:
  keep-presence:
    command: python3 $SNAP/keep-presence.py
    plugs:
      - x11
